# Generated by Django 4.2.29 on 2026-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(default='exit', max_length=400),
            preserve_default=False,
        ),
    ]
