# Generated by Django 4.2.29 on 2026-05-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_fournisseur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_production',
            field=models.DateField(blank=True, null=True),
        ),
    ]
